✨ feat(NeighborhoodAttention2D and NeighborhoodAttention1D):
SHI-Labs/NATTEN pull request #6
Opened 2022-11-21 03:02 UTC by lartpang

Support to remove RPB without side-effects by setting rpb to a buffer tensor.

2022-11-22 22:08 UTC, alihassanijr commented on natten/natten1d.py
> +            self.register_buffer('rpb', torch.zeros(num_heads, (2 * kernel_size - 1)))
```suggestion
        self.rpb = nn.Parameter(torch.zeros(num_heads, (2 * kernel_size - 1)), requires_grad=with_rpb)
        if with_rpb:
            trunc_normal_(self.rpb, std=.02, mean=0., a=-2., b=2.)
```
Could you format it like this instead?

2022-11-22 22:09 UTC, alihassanijr commented on natten/natten2d.py
> +            self.register_buffer('rpb', torch.zeros(num_heads, (2 * kernel_size - 1), (2 * kernel_size - 1)))
```suggestion
        self.rpb = nn.Parameter(torch.zeros(num_heads, (2 * kernel_size - 1), (2 * kernel_size - 1)), requires_grad=with_rpb)
        if with_rpb:
            trunc_normal_(self.rpb, std=.02, mean=0., a=-2., b=2.)
```
Same comment here.

2022-11-22 22:11 UTC, alihassanijr requested changes
Thanks for the PR again.
We actually might just allow for `None` to be passed to the backend in future versions to just skip over the RPB calls, specifically the grad function that is non-deterministic.

But for now, I think we should be good to merge this.
Could you make the changes I requested though?

2022-11-23 04:53 UTC, lartpang commented
@alihassanijr 
Thanks for your reply and the valuable advice.
About the above changes, I'm actually a little confused here.
Besides the more concise form of your proposal, are there some other differences between the two versions?

i.e.:

`self.register_buffer(tensor)` vs `nn.Parameter(tensor, requires_grad=False)`, are they really equivalent??

2022-11-23 05:57 UTC, alihassanijr commented
It is just the preferred way of doing it.
Buffers are exactly that, buffers.
Bias terms are never buffers, they are parameters.
Now the "correct" way of doing it would be to set rpb to `None`, similar to standard torch practice; however that would not work until we modify the backend to support NoneTypes for rpb.

2022-11-23 07:51 UTC, lartpang commented
> Buffers never get stored into state dict, parameters do. 

The `persistent=True` of `register_buffer` will make the buffer be part of the module’s state_dict.

https://pytorch.org/docs/1.8.0/generated/torch.nn.Module.html?highlight=buffer#torch.nn.Module.register_buffer

2022-11-28 18:23 UTC, alihassanijr commented on natten/natten1d.py
> +        if with_rpb:
```suggestion
        if self.bias:
```

2022-11-28 18:23 UTC, alihassanijr commented on natten/natten1d.py
> +        self.with_rpb = with_rpb
```suggestion
        self.bias = bias
```

2022-11-28 18:23 UTC, alihassanijr commented on natten/natten1d.py
> +                 dilation=None, with_rpb=True):
```suggestion
                 dilation=None, bias=True):
```

2022-11-28 18:23 UTC, alihassanijr commented on natten/natten1d.py
> +        return f'kernel_size={self.kernel_size}, dilation={self.dilation}, head_dim={self.head_dim}, num_heads={self.num_heads}, with_rpb={self.with_rpb}'
```suggestion
        return f'kernel_size={self.kernel_size}, dilation={self.dilation}, head_dim={self.head_dim}, num_heads={self.num_heads}, bias={self.bias}'
```

2022-11-28 18:24 UTC, alihassanijr commented on natten/natten2d.py
> +                 dilation=None, with_rpb=True):
```suggestion
                 dilation=None, bias=True):
```

2022-11-28 18:24 UTC, alihassanijr commented on natten/natten2d.py
> +        self.with_rpb = with_rpb
```suggestion
        self.bias = bias
```

2022-11-28 18:25 UTC, alihassanijr commented on natten/natten2d.py
> +        if with_rpb:
```suggestion
        if bias:
```

2022-11-28 18:26 UTC, alihassanijr commented on natten/natten2d.py
> +        return f'kernel_size={self.kernel_size}, dilation={self.dilation}, head_dim={self.head_dim}, num_heads={self.num_heads}, with_rpb={self.with_rpb}'
```suggestion
        return f'kernel_size={self.kernel_size}, dilation={self.dilation}, head_dim={self.head_dim}, num_heads={self.num_heads}, bias={self.rpb.requires_grad}'
```

2022-11-28 18:27 UTC, alihassanijr reviewed
Actually could we refactor `with_rpb` -> `bias` as suggested above?
That would make things easier for future versions.

2022-11-30 02:51 UTC, lartpang commented
@alihassanijr 

Following your suggestion, I committed the latest changes. You can check it out.

2022-11-30 03:11 UTC, alihassanijr commented
Great. Thank you!

2022-11-30 03:12 UTC, merged